name: qumls
channels:
  - conda-forge
  - defaults
dependencies:
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.13.0=py311h511ffe1_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - anyio=4.11.0=pyhcf101f3_0
  - appnope=0.1.4=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-timeout=4.0.3=pyhd8ed1ab_0
  - attrs=25.4.0=pyh71513ae_0
  - brotli-python=1.1.0=py311hf719da1_4
  - bzip2=1.0.8=hd037594_8
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - certifi=2025.10.5=pyhd8ed1ab_0
  - cffi=2.0.0=py311hcfc1310_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - dataclasses-json=0.6.7=pyhd8ed1ab_1
  - debugpy=1.8.17=py311hc58e375_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - frozenlist=1.7.0=py311h8740443_0
  - greenlet=3.2.4=py311hf719da1_1
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - httpx-sse=0.4.3=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=hfee45f7_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.0.0=pyh5552912_0
  - ipython=9.6.0=pyhfa0c392_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - joblib=1.5.2=pyhd8ed1ab_0
  - jsonpatch=1.33=pyhd8ed1ab_1
  - jsonpointer=3.0.0=py311h267d04e_2
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - krb5=1.21.3=h237132a_0
  - langchain=0.3.27=pymin310_h332efcf_1
  - langchain-community=0.3.31=pymin310_h332efcf_0
  - langchain-core=0.3.79=pyhd8ed1ab_0
  - langchain-text-splitters=0.3.11=pyhd8ed1ab_0
  - langsmith=0.3.45=pyhd8ed1ab_1
  - libblas=3.9.0=37_h51639a9_openblas
  - libcblas=3.9.0=37_hb0561ab_openblas
  - libcxx=21.1.3=hf598326_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libexpat=2.7.1=hec049ff_0
  - libffi=3.4.6=h1da3d7d_1
  - libgfortran=15.2.0=hfcf01ff_1
  - libgfortran5=15.2.0=h742603c_1
  - liblapack=3.9.0=37_hd9741b5_openblas
  - liblzma=5.8.1=h39f12f2_2
  - libopenblas=0.3.30=openmp_h60d53f8_2
  - libsodium=1.0.20=h99b78c6_0
  - libsqlite=3.50.4=h4237e3c_0
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=21.1.3=h4a912ad_0
  - marshmallow=3.26.1=pyhd8ed1ab_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - multidict=6.6.3=py311h30e7462_0
  - mypy_extensions=1.1.0=pyha770c72_0
  - ncurses=6.5=h5e97a16_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.5.4=h5503f6c_0
  - orjson=3.11.3=py311h1c3fc1a_1
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py311hdb8e4fa_1
  - parso=0.8.5=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.2=pyh8b19718_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - propcache=0.3.1=py311h4921393_0
  - psutil=7.1.0=py311h9408147_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycparser=2.22=pyh29332c3_1
  - pydantic-core=2.41.4=py311h71babbd_0
  - pydantic-settings=2.11.0=pyh3cfb1c2_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.11.14=hec0b533_1_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-dotenv=1.1.1=pyhe01879c_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.11=8_cp311
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=py311ha9b3269_0
  - pyzmq=27.1.0=py311h13abfa4_0
  - readline=8.2=h1d1bf99_2
  - requests=2.32.5=pyhd8ed1ab_0
  - requests-toolbelt=1.0.0=pyhd8ed1ab_1
  - scikit-learn=1.7.2=py311h0f965f6_0
  - scipy=1.16.2=py311h2734c94_0
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - sniffio=1.3.1=pyhd8ed1ab_1
  - sqlalchemy=2.0.44=py311h9408147_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tenacity=9.1.2=pyhd8ed1ab_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=h892fb3f_2
  - tornado=6.5.2=py311h3696347_1
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing-inspection=0.4.2=pyhd8ed1ab_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - typing_inspect=0.9.0=pyhd8ed1ab_1
  - tzdata=2025b=h78e105d_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - yaml=0.2.5=h925e9cb_3
  - yarl=1.20.1=py311h4921393_0
  - zeromq=4.3.5=h888dc83_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zstandard=0.23.0=py311h3696347_3
  - pip:
      - blis==1.3.0
      - catalogue==2.0.10
      - charset-normalizer==3.4.3
      - click==8.3.0
      - cloudpathlib==0.23.0
      - confection==0.1.5
      - cymem==2.0.11
      - en-core-web-sm==3.8.0
      - fsspec==2024.12.0
      - jinja2==3.1.6
      - jq==1.10.0
      - json-repair==0.44.1
      - langcodes==3.5.0
      - language-data==1.3.0
      - leveldb==0.201
      - marisa-trie==1.3.1
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - mdurl==0.1.2
      - murmurhash==1.0.13
      - neo4j==5.28.2
      - neo4j-graphrag==1.10.1
      - networkx==3.6
      - nltk==3.9.2
      - numpy==2.3.5
      - preshed==3.0.10
      - pydantic==2.12.1
      - pypdf==6.4.0
      - quickumls==1.4.2
      - quickumls-simstring==1.1.5.post1
      - regex==2025.9.18
      - rich==14.2.0
      - shellingham==1.5.4
      - smart-open==7.3.1
      - spacy==3.8.7
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.5.1
      - thinc==8.3.6
      - typer==0.19.2
      - types-pyyaml==6.0.12.20250915
      - unidecode==1.4.0
      - unqlite==0.9.9
      - wasabi==1.1.3
      - weasel==0.4.1
      - wrapt==1.17.3
prefix: /opt/anaconda3/envs/qumls
