name: qumls123
channels:
  - defaults
  - conda-forge
dependencies:
  - annotated-types=0.6.0=py311hecd8cb5_0
  - blas=1.0=openblas
  - brotlicffi=1.0.9.2=py311h6d0c2b6_1
  - bzip2=1.0.8=h6c40b1e_6
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - catalogue=2.0.10=py311hecd8cb5_0
  - certifi=2025.8.3=py311hecd8cb5_0
  - cffi=1.17.1=py311h9205ec4_1
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.2.1=py311hecd8cb5_0
  - cloudpathlib=0.21.0=py311hecd8cb5_0
  - colorama=0.4.6=py311hecd8cb5_0
  - confection=0.1.5=py311he13d532_0
  - cymem=2.0.6=py311h6d0c2b6_1
  - cython-blis=1.0.1=py311h46256e1_0
  - expat=2.7.1=h6d0c2b6_0
  - idna=3.7=py311hecd8cb5_0
  - jinja2=3.1.6=py311hecd8cb5_0
  - langcodes=3.3.0=pyhd3eb1b0_0
  - leveldb=1.18=0
  - libcxx=19.1.7=haebbb44_3
  - libffi=3.4.4=hecd8cb5_1
  - libgfortran=5.0.0=11_3_0_hecd8cb5_28
  - libgfortran5=11.3.0=h9dfd629_28
  - libopenblas=0.3.29=h3f8574a_0
  - llvm-openmp=19.1.7=h5048363_2
  - markdown-it-py=2.2.0=py311hecd8cb5_1
  - markupsafe=3.0.2=py311h46256e1_0
  - mdurl=0.1.0=py311hecd8cb5_0
  - murmurhash=1.0.12=py311h6d0c2b6_0
  - ncurses=6.5=h923df54_0
  - numpy=2.3.1=py311hc3ad23b_0
  - numpy-base=2.3.1=py311heda3e1f_0
  - openssl=3.5.2=h6e31bce_0
  - packaging=25.0=py311hecd8cb5_0
  - pip=25.2=pyhc872135_0
  - preshed=3.0.9=py311h6d0c2b6_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pydantic=2.11.7=py311hecd8cb5_0
  - pydantic-core=2.33.2=py311hb0c8e1d_0
  - pygments=2.19.1=py311hecd8cb5_0
  - pysocks=1.7.1=py311hecd8cb5_0
  - python=3.11.13=hbff2529_0
  - python-leveldb=0.201=py311hdf8f085_5
  - python_abi=3.11=2_cp311
  - readline=8.3=h49f2429_0
  - requests=2.32.4=py311hecd8cb5_0
  - rich=13.9.4=py311hecd8cb5_0
  - setuptools=72.1.0=py311hecd8cb5_0
  - shellingham=1.5.0=py311hecd8cb5_0
  - six=1.17.0=py311hecd8cb5_0
  - smart_open=5.2.1=py311hecd8cb5_0
  - snappy=1.2.2=h25c286d_0
  - spacy=3.8.2=py311h1962661_0
  - spacy-legacy=3.0.12=py311hecd8cb5_0
  - spacy-loggers=1.0.4=py311hecd8cb5_0
  - sqlite=3.50.2=hc8b0dd6_1
  - srsly=2.5.1=py311h6d0c2b6_0
  - thinc=8.3.2=py311h1962661_1
  - tk=8.6.15=h3a5a201_0
  - tqdm=4.67.1=py311h85bffb1_0
  - typer=0.9.0=py311hecd8cb5_0
  - typing-extensions=4.12.2=py311hecd8cb5_0
  - typing-inspection=0.4.0=py311hecd8cb5_0
  - typing_extensions=4.12.2=py311hecd8cb5_0
  - tzdata=2025b=h04d1e81_0
  - urllib3=2.5.0=py311hecd8cb5_0
  - wasabi=0.9.1=py311hecd8cb5_0
  - weasel=0.4.1=py311hecd8cb5_0
  - wheel=0.45.1=py311hecd8cb5_0
  - xz=5.6.4=h46256e1_1
  - zlib=1.2.13=h4b97444_1
  - pip:
      - en-core-web-sm==3.8.0
      - joblib==1.5.2
      - nltk==3.9.1
      - quickumls==1.4.2
      - quickumls-simstring==1.1.5.post1
      - regex==2025.9.1
      - unidecode==1.4.0
      - unqlite==0.9.9
